### ISSUE TITLE
[Plugin] Implement required metric plugins

### ISSUE THREAD

**Issue by rafalpotempa** [software-engineering-labs-group-5/image-similarity#22]
Implement required metric plugins:

- [x] PSNR - Peak Signal-to-Noise Ratio
- [x] RMSE - Root Mean Square Error
- [x] cPSNR - [link](https://kelvins.esa.int/proba-v-super-resolution/scoring/) (without Z score)
- [x] FSIM - Feature-based Similarity Index
- [x] SSIM - Structural Similarity Index

See _Analysis and project requirements_ for more details.

Related PRs 
https://github.com/software-engineering-labs-group-5/image-similarity/pull/20

**Comment by ttarasiewicz** [comment]
![image](https://user-images.githubusercontent.com/17416539/101017752-cdc55800-356a-11eb-8f76-4c851216000d.png)

**Comment by ttarasiewicz** [comment]
Co do powyższej metryki zapomniałem dodać, że w Państwa przypadku niepotrzebny jest obraz hr_mask, więc wszystkie obliczenia z nim związane można pominąć, a zmienna nazwana tutaj 'total_pixels_masked' będzie przechowywać tylko całkowitą ilość pikseli w obrazie. Zauważcie też, że w tym przykładzie obrazy są używane jako macierze 4D w formacie NCHW (ponieważ liczonych jest kilka obrazów jednocześnie, a kanały są na drugiej pozycji, tzw. channel first format) - powinniście pominąć pierwszy wymiar i pracować na macierzach 3D w formacie HWC (tzw. channel last).
